[build-system]
requires = [
    "cmake>=3.19",
    "numpy>=1.21.2",
    "scikit-build-core >=0.4.3",
    "ninja; platform_system!='Windows'"
]

build-backend = "scikit_build_core.build"

[project]
name = "finufft"
version = "0.0.1"
description = "Python bindings for the FINUFFT C++ library"
readme = "README.md"
requires-python = ">=3.8"

[tool.scikit-build]
# Protect the configuration against future changes in scikit-build-core
minimum-version = "0.4"
cmake.targets = ["finufft"]
cmake.args = ['-DFINUFFT_BUILD_PYTHON=ON', '-DCMAKE_BUILD_TYPE=Release'] # not sure if this is necessary
wheel.packages = ["python/finufft/finufft"]
wheel.exclude = ["**.pyx"]
# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"
# Build stable ABI wheels for CPython 3.8+
wheel.py-api = "cp38"
[tool.cibuildwheel]
# Necessary to see build output from the actual compilation
build-verbosity = 1
