name: Build and test Python wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.buildplat[0] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - [ ubuntu-22.04, manylinux_x86_64 ]
          - [ windows-2019, win_amd64 ]
        python: [ "cp310", "cp311", "cp312", "cp313" ] # exclude pp313t for now
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Build wheels ${{ matrix.python }}-${{ matrix.buildplat[1] }}
        uses: pypa/cibuildwheel@v2.22.0
        with:
          package-dir: 'python/cufinufft'
        env:
          CIBW_BEFORE_ALL_LINUX: |
            if command -v yum &> /dev/null; then
              yum install -y epel-release
              yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo
              yum install -y cuda-11-4
            else
              echo "Unsupported package manager. Exiting."
              exit 1
            fi
          CIBW_ENVIRONMENT_LINUX: PATH=$PATH:/usr/local/cuda/bin LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
          CIBW_BEFORE_ALL_WINDOWS: |
            Invoke-WebRequest https://developer.download.nvidia.com/compute/cuda/11.4.0/network_installers/cuda_11.4.0_win10_network.exe -OutFile cuda_toolkit_windows.exe
            Start-Process -Wait -FilePath .\cuda_toolkit_windows.exe -ArgumentList "-s cufft_11.4 thrust_11.4 nvcc_11.4 cudart_11.4"
            Remove-Item .\cuda_toolkit_windows.exe
#            $CUDA_PATH = "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4"
#            echo "CUDA_PATH=$CUDA_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
#            echo "CUDA_PATH_V12_5=$CUDA_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
#            echo "$CUDA_PATH/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          CIBW_ENVIRONMENT_WINDOWS: CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Tosolkit\CUDA\v11.4
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          CIBW_TEST_COMMAND: "echo 'Wheel installed'"
          CIBW_BUILD_FRONTEND: "pip; args: --no-deps"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl
