name: Build Python wheels (skbuild)

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]

    steps:
      - uses: actions/checkout@v4


      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        env:
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_SKIP_LINUX: "pp* *musllinux*"
          CIBW_BEFORE_ALL_LINUX: yum install -y fftw3-devel
          CIBW_BEFORE_ALL_MACOS: brew install gcc libomp fftw
          CIBW_ENVIRONMENT_MACOS: "FC=gfortran-11 CC=gcc-11 CXX=g++-11 OpenMP_ROOT=/usr/local/opt/libomp"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
