name: Test python skbuild with CMake

on: [push, pull_request]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate matrix
        id: generate_matrix
        run: |
          MATRIX=$(python3 ../.github/workflows/generate_matrix.py)
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
  build:
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.platform, 'windows') }}
          cmake: false
          ninja: false
          vcpkg: false
          cppcheck: false
          clangtidy: false

      - name: Install pytest
        run: python -m pip install pytest
      - name: Set min macOS version
        if: runner.os == 'macOS'
        run: |
          echo "MACOS_DEPLOYMENT_TARGET=10.14" >> $GITHUB_ENV
      - name: Set compiler flags
        run: |
          echo CMAKE_ARGS="-DFINUFFT_ARCH_FLAGS=${{ matrix.arch_flags }}" >> $GITHUB_ENV
      - name: Build
        run: pip install .
      - name: Test
        run: python -m pytest python/finufft/test
