name: Pip

on: [push, pull_request]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create matrix
        id: create_matrix
        uses: fabiocaccamo/create-matrix-action@v3
        with:
          matrix: |
            os {windows-latest}, compiler {msvc, llvm}, arch_flags {/arch:AVX2, /arch:AVX512}, python-version {3.8, 3.11} 
            os {ubuntu-latest}, compiler {gcc, llvm}, arch_flags {-march=native, -march=x86-64}, python-version {3.8, 3.11}

    outputs:
      matrix: ${{ steps.create_matrix.outputs.matrix }}
  build:
    name: Build with Pip
    runs-on: ${{ matrix.os }}
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: false
          ninja: false
          vcpkg: false
          cppcheck: false
          clangtidy: false

      - name: Install pytest
        run: python -m pip install pytest
      - name: Set min macOS version
        if: runner.os == 'macOS'
        run: |
          echo "MACOS_DEPLOYMENT_TARGET=10.14" >> $GITHUB_ENV
      - name: Set compiler flags
        run: |
          echo MAKE_ARGS="-DFINUFFT_ARCH_FLAGS=${{ matrix.arch_flags }}" >> $GITHUB_ENV
      - name: Build
        run: pip install . --verbose
      - name: Test
        run: python -m pytest python/finufft/test
