name: Build Python wheels (skbuild)

on: [push, pull_request]

jobs:
  build_wheels_unix:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]

    steps:
      - uses: actions/checkout@v4


      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: "pp* *musllinux*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_BEFORE_ALL_LINUX: yum install -y fftw3-devel
          CIBW_BEFORE_ALL_MACOS: brew install gcc@14 fftw
          CIBW_ENVIRONMENT_MACOS: >
            FC=gfortran-14
            CC=gcc-14
            CXX=g++-14
            MACOSX_DEPLOYMENT_TARGET=13
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {project}/python/finufft/test

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_wheels_macos_arm64:
    name: Build wheels on macos-14
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_MACOS: "arm64"
          CIBW_BEFORE_ALL_MACOS: |
            pkg=$(brew fetch --force --bottle-tag=arm64_ventura fftw | grep 'Downloaded to' | cut -d' ' -f3)
            brew install $pkg
            pkg=$(brew fetch --force --bottle-tag=arm64_ventura gcc | grep 'Downloaded to' | cut -d' ' -f3)
            brew install $pkg
          CIBW_ENVIRONMENT_MACOS: >
            CC=gcc-14
            CXX=g++-14
            MACOSX_DEPLOYMENT_TARGET=14
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {project}/python/finufft/test

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-macos-arm64
          path: ./wheelhouse/*.whl

  build_wheels_win:
    name: Build wheels on windows
    runs-on: windows-latest
    env:
      fftw-version: 3.3.10

    steps:
      - uses: actions/checkout@v4

      - name: Cache FFTW
        id: cache-fftw
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/fftw"
          key: ${{ runner.os }}-build-fftw${{ env.fftw-version }}

      - name: Install FFTW
        if: steps.cache-fftw.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri "https://www.fftw.org/fftw-${{ env.fftw-version}.tar.gz" -OutFile "${{ github.workspace }}\fftw.tar.gz"

          New-Item -Path "${{ github.workspace }}" -Name "fftw-source" -ItemType Directory
          tar --strip-components=1 -C "${{ github.workspace }}\fftw-source" -zxf "${{ github.workspace }}\fftw.tar.gz"

          cmake -S "${{ github.workspace }}\fftw-source" -D CMAKE_INSTALL_PREFIX="${{ github.workspace }}\fftw" -D ENABLE_AVX2=ON -D BUILD_TESTS=OFF -D BUILD_SHARED_LIBS=OFF -D ENABLE_OPENMP=ON -D ENABLE_FLOAT=OFF -B "${{ github.workspace }}\fftw-build"
          cmake --build "${{ github.workspace }}\fftw-build" --config Release
          cmake --install "${{ github.workspace }}\fftw-build"

          cmake -S "${{ github.workspace }}\fftw-source" -D CMAKE_INSTALL_PREFIX="${{ github.workspace }}\fftw" -D ENABLE_AVX2=ON -D BUILD_TESTS=OFF -D BUILD_SHARED_LIBS=OFF -D ENABLE_OPENMP=ON -D ENABLE_FLOAT=ON -B "${{ github.workspace }}\fftw-build"
          cmake --build "${{ github.workspace }}\fftw-build" --config Release
          cmake --install "${{ github.workspace }}\fftw-build"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: AMD64
          CIBW_ENVIRONMENT: >
            FFTWDIR='${{ github.workspace }}\fftw'
            CC=clang-cl
            CXX=clang-cl
          CIBW_BEFORE_BUILD: env
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {project}/python/finufft/test
          # PyPy 3.10 triggers access violation under Windows, for some reason.
          CIBW_TEST_SKIP: "pp310-win*"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-windows
          path: ./wheelhouse/*.whl
